### ISSUE TITLE
ModuleNotFoundError: No module named 'tap_airtable.services'

### ISSUE THREAD

**Issue by andresbravog** [aimementoring/tap-airtable#11]
On a fresh install using the code from your master branch I'm getting:

```
Traceback (most recent call last):
  File "/Users/andresbravogorgonio/opt/anaconda3/bin/tap-airtable", line 5, in <module>
    from tap_airtable import main
  File "/Users/andresbravogorgonio/opt/anaconda3/lib/python3.8/site-packages/tap_airtable/__init__.py", line 2, in <module>
    from tap_airtable.services import Airtable
ModuleNotFoundError: No module named 'tap_airtable.services'
```

**Comment by NiallRees** [comment]
Did you manage to work this out @andresbravog?
